[package]
name = "auto-bridge"
version = "0.1.5"
authors = ["Jehan <jehan.tremback@gmail.com>, Justin <justin@althea.net>"]
edition = "2018"

[dependencies]
web30 = { git = "https://github.com/althea-net/web30", rev = "ced518b6a3f82756e46bf061f5eb547695cbe868" }
futures = "0.3"
failure = "0.1"
num256 = "0.2"
clarity = "0.1"
rand = "0.7"
num = "0.3"
log = "0.4"
async-std = "1.6"

[dev-dependencies]
actix = "0.9"
