[package]
name = "auto-bridge"
version = "0.1.5"
authors = ["Jehan <jehan.tremback@gmail.com>, Justin <justin@althea.net>"]
edition = "2018"

[dependencies]
web30 = "0.6"
futures = "0.3"
failure = "0.1"
num256 = "0.2"
clarity = "0.1"
rand = "0.7"
num = "0.3"
log = "0.4"
tokio = {version = "0.2", default_features = false, features = ["time"]}

[dev-dependencies]
actix = "0.10"
