[package]
name = "rita_tower"
version = "0.18.0"
edition = "2018"
license = "Apache-2.0"

[dependencies]
althea_types = { path = "../althea_types"}
lazy_static = "1.4"
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
log = { version = "0.4", features = ["release_max_level_info"] }
