[target.x86_64-unknown-linux-gnu]
image = "cross-with-clang-ssl"
[target.x86_64-unknown-linux-musl]
image = "cross-with-clang-ssl"

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "RUSTFLAGS",
]