[package]
name = "array_serialization_derive"
version = "0.1.0"
authors = ["Jehan <jehan.tremback@gmail.com>"]

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
base64 = "0.9.0"
hex = "0.3.1"
serde = "1.0.26"
serde_json = "1.0.8"
serde_derive = "1.0.26"

[lib]
proc-macro = true